### ISSUE TITLE
CSS selector as a tag method argument

### ISSUE THREAD

**Issue by Janther** [atom/space-pen#35]
Having a look at the following method 

``` CoffeeScript
  extractOptions: (args) ->
    options = {}
    for arg in args
      switch typeof(arg)
        when 'function'
          options.content = arg
        when 'string', 'number'
          options.text = arg.toString()
        else
          options.attributes = arg
    options
```

I think it would be interesting to add the following change:

``` CoffeeScript
  extractOptions: (args) ->
    options = {}
    for arg in args
      switch typeof(arg)
        when 'function'
          options.content = arg
        when 'string', 'number'
          options.text = arg.toString()
        # CSS selector #
        when 'array'
          options.selector = arg.join('.')
        else
          options.attributes = arg
    options
```

This way one could write something like this:

``` CoffeeScript
# before makeup
@a id: "submit", class: "button shinny", href: "http:example,com", "Submit"
# after
@a ["#submit.button.shinny"], href: "http:example,com", "Submit"
# or
@a ["#submit", "button.shinny"], href: "http:example,com", "Submit"
# or even
@a ["#submit", "button", "shinny"], href: "http:example,com", "Submit"
```

It would be reverse compatible with the current DSL while providing a closer CSS selector approach.
Also if you don't use the array selector it shouldn't impact much current performance.

Sorry I'm coming from HAML world and feel more comfortable with that notation, but I think I'm not the only one that would benefit from this.

Tell me if you like this and I can propose a pull request.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/space-pen), this package is no longer maintained and is deprecated. We recommend that people use the [etch package](https://github.com/atom/etch) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
