### ISSUE TITLE
Current dependencies

### ISSUE THREAD

**Issue by avanderhoorn** [atom/space-pen#45]
I'm really like that space-pen works and am trying to really use it in anger for client side web development. I know that this mightn't be its current primary use, but I think it has a lot of potential. The main thing that I keep scratching my head on is the dependency on `jqeury`, `jquery extensions`, `underscore` and `underscore extensions`. 

I understand why these exist and that they make life extremely covenant but I'm wondering if the core of space-pen actually needs this. The question that I'm wondering is what functions does the actual core engine itself need to work vs how much is nice for devs to work with when using space-pen. If the core didn't depend on these, the overall amount of bytes one needs to use space-pen is reduced dramatically. 

To start with, from what I can tell, very few of the methods in `jQuery extensions` are actually used, and the only function in `underscore plus` used is `humanizeEventName` and likewise with `underscore` the only one used is `extend`. From this quick look, it would appear that `underscore` and `underscore-plus` could be removed as a core dependency saving around 20kb and another 4-5kb saved by removing `jQuery extensions`. 

Removing `jQuery` on the surface seems like its a bit more difficult, given that it inherits from view. But putting aside for a moment, the only functions in `jQuery` itself that seem to be in use is `data` and `on`, the former seems like it could be removed fairly easily and I'm wondering if the later could be an enhancement. As for the view being an actual `jQuery` object, could this also be treaded as an optional enhancement if `jQuery` exists. In my case, I could `jQuery` or one of the jQuery-compatible APIs if I want/need.

So, knowing space-pen more than I, do you think that this would be possible, could the current extra code that isn't need by core but needed by `atom` be abstracted out and included just it in another way?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/space-pen), this package is no longer maintained and is deprecated. We recommend that people use the [etch package](https://github.com/atom/etch) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
