### ISSUE TITLE
Simplify removing a listener

### ISSUE THREAD

**Issue by bolinfest** [atom/space-pen#51]
From [this discussion](https://discuss.atom.io/t/is-there-a-sane-way-to-remove-event-handlers-using-spacepen-jquery/11495/), it sounds like the goal is to use [Emitter](https://github.com/atom/emissary/blob/master/src/emitter.coffee) as a mixin for SpacePen's [View](https://github.com/atom/space-pen/blob/master/src/space-pen.coffee) so that `on()` returns a `Subscription` that has an `off()` method that can be used to remove the listener.

I worry that this is going to be a bit of a pain because [space-pen-extensions.coffee](https://github.com/atom/atom/blob/master/src/space-pen-extensions.coffee) already mixes in a similar class:

```
Subscriber.includeInto(spacePen.View)
```

Currently, the implementation of `command()` is `super(commandName, selector, options, handler)`, which I believe delegates to this method:

```
$.fn.command = (eventName, selector, options, handler) ->
  if not options?
    handler  = selector
    selector = null
  else if not handler?
    handler = options
    options = null

  if selector? and typeof(selector) is 'object'
    options  = selector
    selector = null

  @document(eventName, _.humanizeEventName(eventName, options?['doc']))
  @on(eventName, selector, options?['data'], handler)
```

So perhaps, at least as a stopgap, this method could return an object with an `off()` method that removes the listener (and releases appropriate references), and at some point in the future, the return value could be a true `Subscription`, which would have the same contract? As it stands today, SpacePen appears to have minimal dependencies (`underscore-plus` being the only one), so it would be nice to be able to get this feature today without having to wait for all of this jQuery/Emitter/Subscription stuff to be figured out.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom-archive/space-pen), this package is no longer maintained and is deprecated. We recommend that people use the [etch package](https://github.com/atom/etch) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
